### ISSUE TITLE
URI namespace of specification elements breaks OGC-NA policy

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/cdb-volume-4#1]
URI namespace of specification elements breaks OGC-NA policy

CDB 1.1  Volume 4 states that:

```
The normative provisions in this standard are denoted by the URI

    http://www.opengis.net/spec/cdb/1.1/shapefile

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

For the sake of brevity, the use of “req” in a requirement URI denotes:

    http://www.opengis.net/spec/cdb/1.1/shapefile

An example might be:

   req/shapefile/storage
```

The text above does not comply with OGC-NA policy. Please see Sections 5.3 and 5.4 of OGC-NA Name type specification - specification elements (10-103) http://portal.opengeospatial.org/files/?artifact_id=39194

The text implies that ‘req’ replaces 'http://www.opengis.net/spec/cdb/1.1/shapefile’.

To fix this, I recommend that the text be changed to say.

```
The normative provisions in this standard are denoted by the URI namespace

    http://www.opengis.net/spec/cdb/1.1/shapefile

All requirements that appear in this document are denoted by partial URIs which are relative to the namespace shown above.

For the sake of brevity, the use of “req” in a requirement URI denotes:
      http://www.opengis.net/spec/cdb/1.1/shapefile/req

All conformance tests that appear in this document are denoted by partial URIs which are relative to the namespace shown above.

For the sake of brevity, the use of “conf” in a requirement URI denotes:
        http://www.opengis.net/spec/cdb/1.1/shapefile/conf

```

This issue may affect CDB 1.2 as well. So that document needs to be checked too.

**Comment by ghobona** [comment]
Please also note that Annex A (page 11) introduces the namespace `http://www.opengis.net/spec/cdb-shapefile/1.0/conf/`.

This additional namespace should be removed, so that all specification elements derive their namespaces from the same base.

**Comment by cnreediii** [comment]
Corrected as recommended.

**Comment by DavidFLOR** [comment]
Updated in V1.3
